In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  532621.000000  532621.000000  397924.000000
mean       10.239972       3.847621   15294.315171
std       159.593551      41.758023    1713.169877
min     -9600.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13969.000000
50%         3.000000       2.080000   15159.000000
75%        10.000000       4.130000   16795.000000
max     80995.000000   13541.330000   18287.000000

In [2]:
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

In [3]:
basket = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

In [5]:
basket

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581279,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

basket_sets = basket.applymap(encode_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [8]:
basket_sets.describe()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,...,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,0.030612,0.015306,0.002551,0.005102,0.015306,0.017857,0.017857,0.002551,0.022959,0.015306,...,0.007653,0.005102,0.002551,0.002551,0.002551,0.017857,0.002551,0.010204,0.002551,0.005102
std,0.172485,0.122924,0.050508,0.071337,0.122924,0.132601,0.132601,0.050508,0.149965,0.122924,...,0.087258,0.071337,0.050508,0.050508,0.050508,0.132601,0.050508,0.100627,0.050508,0.071337
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

In [10]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.096939,0.102041,0.073980,0.763158,7.478947,0.064088,3.791383
1,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102041,0.096939,0.073980,0.725000,7.478947,0.064088,3.283859
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
3,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
4,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED),0.102041,0.094388,0.073980,0.725000,7.681081,0.064348,3.293135

In [11]:
rules[ (rules['lift'] >= 6) &
       (rules['confidence'] >= 0.8) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
3,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
17,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS),0.127551,0.132653,0.102041,0.800000,6.030769,0.085121,4.336735
18,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
19,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
20,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796
21,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
22,"(SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.122449,0.132653,0.099490,0.812500,6.125000,0.083247,4.625850

In [12]:
basket['ALARM CLOCK BAKELIKE GREEN'].sum()

340.0

basket['ALARM CLOCK BAKELIKE RED'].sum()

316.0

316.0

In [13]:
basket2 = (df[df['Country'] =="Germany"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

basket_sets2 = basket2.applymap(encode_units)
basket_sets2.drop('POSTAGE', inplace=True, axis=1)
frequent_itemsets2 = apriori(basket_sets2, min_support=0.05, use_colnames=True)
rules2 = association_rules(frequent_itemsets2, metric="lift", min_threshold=1)

rules2[ (rules2['lift'] >= 4) &
        (rules2['confidence'] >= 0.5)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN WOODLAND ANIMALS),0.115974,0.137856,0.067834,0.584906,4.242887,0.051846,2.076984
7,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.107221,0.137856,0.061269,0.571429,4.145125,0.046488,2.011670
10,(RED RETROSPOT CHARLOTTE BAG),(WOODLAND CHARLOTTE BAG),0.070022,0.126915,0.059081,0.843750,6.648168,0.050194,5.587746

In [14]:
#2

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import mlxtend as ml

In [1]:
#3

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori
dataset = pd.read_csv("E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/work.csv")
dataset

,apples,artichok,avocado,baguette,bordeaux,bourbon,chicken,coke,corned_b,cracker,ham,heineken,hering,ice_crea,olives,peppers,sardines,soda,steak,turkey
0,NaN,NaN,NaN,NaN,NaN,bourbon,NaN,NaN,corned_b,NaN,ham,NaN,hering,ice_crea,olives,NaN,NaN,NaN,NaN,turkey
1,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,cracker,NaN,heineken,hering,NaN,olives,NaN,NaN,soda,NaN,NaN
2,NaN,artichok,avocado,NaN,NaN,NaN,NaN,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,sardines,NaN,NaN,turkey
3,NaN,NaN,NaN,NaN,NaN,bourbon,NaN,coke,NaN,NaN,ham,NaN,NaN,ice_crea,olives,peppers,NaN,NaN,NaN,turkey
4,apples,NaN,avocado,NaN,NaN,NaN,NaN,NaN,corned_b,NaN,NaN,NaN,hering,NaN,olives,NaN,NaN,NaN,steak,turkey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,NaN,artichok,avocado,NaN,NaN,bourbon,chicken,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,apples,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,NaN,ham,NaN,hering,NaN,olives,NaN,NaN,NaN,NaN,turkey
998,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,NaN,cracker,NaN,heineken,hering,NaN,NaN,NaN,sardines,soda,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,chicken,coke,corned_b,NaN,NaN,heineken,NaN,ice_crea,NaN,peppers,sardines,NaN,NaN,NaN
1000,apples,NaN,NaN,NaN,NaN,bourbon,NaN,NaN,corned_b,NaN,NaN,heineken,hering,NaN,olives,NaN,NaN,NaN,steak,NaN

In [14]:
transactions = []
for i in range(0, 1001):
    transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

In [15]:
rules = apriori(transactions, min_support = 0.003, min_confidence = 95, min_lift = 3, min_length = 2)

In [17]:
# Visualizing the list of rules
results = list(rule_list)
for i in results:
    print('\n')
    print(i)
    print('**********')

NameError: name 'rule_list' is not defined

In [16]:
print(rules)

<generator object apriori at 0x000000ACB74C9D48>

In [6]:
frequent_itemsets = apriori(dataset, min_support=0.07, use_colnames=True)
frequent_itemsets

In [7]:
RelationRecord(items=frozenset({'baby', 'milk', 'meat'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baby', 'milk'}), items_add=frozenset({'meat'}), confidence=0.41666666666666663, lift=3.215449245541838)]),

NameError: name 'RelationRecord' is not defined

In [9]:
RelationRecord(items=frozenset({'baby', 'milk', 'meat'})

SyntaxError: unexpected EOF while parsing (<ipython-input-9-55e50fe3544c>, line 1)

# basket analysis using aprior algorithm

In [9]:


# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

In [18]:
# Data Preprocessing
dataset=pd.read_csv('E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/work.csv')

In [19]:
dataset.describe().transpose()

         count unique       top freq
apples     314      1    apples  314
artichok   305      1  artichok  305
avocado    363      1   avocado  363
baguette   392      1  baguette  392
bordeaux    74      1  bordeaux   74
bourbon    403      1   bourbon  403
chicken    315      1   chicken  315
coke       296      1      coke  296
corned_b   391      1  corned_b  391
cracker    488      1   cracker  488
ham        305      1       ham  305
heineken   600      1  heineken  600
hering     486      1    hering  486
ice_crea   313      1  ice_crea  313
olives     473      1    olives  473
peppers    296      1   peppers  296
sardines   296      1  sardines  296
soda       318      1      soda  318
steak      227      1     steak  227
turkey     283      1    turkey  283

In [20]:
dataset

,apples,artichok,avocado,baguette,bordeaux,bourbon,chicken,coke,corned_b,cracker,ham,heineken,hering,ice_crea,olives,peppers,sardines,soda,steak,turkey
0,NaN,NaN,NaN,NaN,NaN,bourbon,NaN,NaN,corned_b,NaN,ham,NaN,hering,ice_crea,olives,NaN,NaN,NaN,NaN,turkey
1,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,cracker,NaN,heineken,hering,NaN,olives,NaN,NaN,soda,NaN,NaN
2,NaN,artichok,avocado,NaN,NaN,NaN,NaN,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,sardines,NaN,NaN,turkey
3,NaN,NaN,NaN,NaN,NaN,bourbon,NaN,coke,NaN,NaN,ham,NaN,NaN,ice_crea,olives,peppers,NaN,NaN,NaN,turkey
4,apples,NaN,avocado,NaN,NaN,NaN,NaN,NaN,corned_b,NaN,NaN,NaN,hering,NaN,olives,NaN,NaN,NaN,steak,turkey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,NaN,artichok,avocado,NaN,NaN,bourbon,chicken,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,apples,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,NaN,ham,NaN,hering,NaN,olives,NaN,NaN,NaN,NaN,turkey
998,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,NaN,cracker,NaN,heineken,hering,NaN,NaN,NaN,sardines,soda,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,chicken,coke,corned_b,NaN,NaN,heineken,NaN,ice_crea,NaN,peppers,sardines,NaN,NaN,NaN
1000,apples,NaN,NaN,NaN,NaN,bourbon,NaN,NaN,corned_b,NaN,NaN,heineken,hering,NaN,olives,NaN,NaN,NaN,steak,NaN

In [21]:
transactions=[]
for i in range(0,1000):
    transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

In [22]:
rule_list = apriori(transactions, min_support = 0.02, min_confidence = 0.95, min_lift = 3, min_length = 2)

In [23]:
# Visualizing the list of rules
results = list(rule_list)
for i in results:
    print('\n')
    print(i)
    print('**********')

RelationRecord(items=frozenset({'apples', 'avocado', 'peppers', 'sardines'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'sardines'}), items_add=frozenset({'peppers'}), confidence=0.9782608695652174, lift=3.3049353701527617), OrderedStatistic(items_base=frozenset({'peppers', 'avocado', 'sardines'}), items_add=frozenset({'apples'}), confidence=0.9574468085106382, lift=3.0589354904493233)])
**********


RelationRecord(items=frozenset({'apples', 'peppers', 'baguette', 'sardines'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baguette', 'peppers', 'sardines'}), items_add=frozenset({'apples'}), confidence=0.9677419354838709, lift=3.0918272699165206)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'turkey', 'ice_crea'}), support=0.096, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'bourbon', 'turkey'}), items_add=frozenset({'ice_crea'}), confidence=0.9795918367346939, lift=3.12968637934407), OrderedStatistic(items_base=frozenset({'ice_crea', 'bourbon', 'turkey'}), items_add=frozenset({'coke'}), confidence=0.9696969696969697, lift=3.2760032760032765)])
**********


RelationRecord(items=frozenset({'chicken', 'coke', 'ham', 'ice_crea'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ham', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=0.9523809523809523, lift=3.2175032175032174)])
**********


RelationRecord(items=frozenset({'chicken', 'coke', 'ice_crea', 'heineken'}), support=0.116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9830508474576273, lift=3.140737531813506), OrderedStatistic(items_base=frozenset({'chicken', 'ice_crea', 'heineken'}), items_add=frozenset({'coke'}), confidence=0.9747899159663866, lift=3.2932091755621173)])
**********


RelationRecord(items=frozenset({'chicken', 'coke', 'sardines', 'heineken'}), support=0.116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'heineken'}), items_add=frozenset({'sardines'}), confidence=0.9830508474576273, lift=3.3211177278973896), OrderedStatistic(items_base=frozenset({'chicken', 'sardines', 'heineken'}), items_add=frozenset({'coke'}), confidence=0.9747899159663866, lift=3.2932091755621173), OrderedStatistic(items_base=frozenset({'coke', 'sardines', 'heineken'}), items_add=frozenset({'chicken'}), confidence=0.9666666666666668, lift=3.0687830687830693)])
**********


RelationRecord(items=frozenset({'chicken', 'coke', 'sardines', 'ice_crea'}), support=0.116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'sardines'}), items_add=frozenset({'ice_crea'}), confidence=0.9914529914529915, lift=3.167581442341826), OrderedStatistic(items_base=frozenset({'chicken', 'sardines', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=1.0, lift=3.3783783783783785)])
**********


RelationRecord(items=frozenset({'chicken', 'sardines', 'ham', 'ice_crea'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ham', 'ice_crea'}), items_add=frozenset({'sardines'}), confidence=0.9523809523809523, lift=3.2175032175032174)])
**********


RelationRecord(items=frozenset({'chicken', 'sardines', 'ice_crea', 'heineken'}), support=0.116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ice_crea', 'heineken'}), items_add=frozenset({'sardines'}), confidence=0.9747899159663866, lift=3.2932091755621173), OrderedStatistic(items_base=frozenset({'chicken', 'sardines', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9747899159663866, lift=3.1143447794453247)])
**********


RelationRecord(items=frozenset({'coke', 'sardines', 'ice_crea', 'heineken'}), support=0.117, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'sardines', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9750000000000001, lift=3.1150159744408947), OrderedStatistic(items_base=frozenset({'heineken', 'sardines', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=0.951219512195122, lift=3.2135794330916285)])
**********


RelationRecord(items=frozenset({'coke', 'turkey', 'sardines', 'ice_crea'}), support=0.025, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'turkey', 'sardines'}), items_add=frozenset({'ice_crea'}), confidence=0.9615384615384617, lift=3.072007864340133)])
**********


RelationRecord(items=frozenset({'avocado', 'heineken', 'apples', 'hering', 'artichok'}), support=0.022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'hering', 'heineken'}), items_add=frozenset({'artichok'}), confidence=0.9565217391304347, lift=3.1361368496079827)])
**********


RelationRecord(items=frozenset({'avocado', 'peppers', 'apples', 'baguette', 'sardines'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'sardines'}), items_add=frozenset({'baguette', 'peppers'}), confidence=0.9782608695652174, lift=7.037847982483578), OrderedStatistic(items_base=frozenset({'apples', 'peppers', 'sardines'}), items_add=frozenset({'baguette', 'avocado'}), confidence=0.989010989010989, lift=4.600051111679019), OrderedStatistic(items_base=frozenset({'peppers', 'avocado', 'sardines'}), items_add=frozenset({'apples', 'baguette'}), confidence=0.9574468085106382, lift=6.513243595310464), OrderedStatistic(items_base=frozenset({'baguette', 'peppers', 'sardines'}), items_add=frozenset({'apples', 'avocado'}), confidence=0.9677419354838709, lift=6.962172197725689), OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'peppers', 'baguette'}), items_add=frozenset({'sardines'}), confidence=0.9782608695652174, lift=3.3049353701527617), OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'baguette', 'sardines'}), items_add=frozenset({'peppers'}), confidence=0.9782608695652174, lift=3.3049353701527617), OrderedStatistic(items_base=frozenset({'baguette', 'avocado', 'peppers', 'sardines'}), items_add=frozenset({'apples'}), confidence=0.989010989010989, lift=3.1597795176069936)])
**********


RelationRecord(items=frozenset({'avocado', 'peppers', 'nan', 'apples', 'sardines'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'sardines'}), items_add=frozenset({'peppers', 'nan'}), confidence=0.9782608695652174, lift=3.3049353701527617), OrderedStatistic(items_base=frozenset({'peppers', 'avocado', 'sardines'}), items_add=frozenset({'apples', 'nan'}), confidence=0.9574468085106382, lift=3.0589354904493233), OrderedStatistic(items_base=frozenset({'apples', 'avocado', 'sardines', 'nan'}), items_add=frozenset({'peppers'}), confidence=0.9782608695652174, lift=3.3049353701527617), OrderedStatistic(items_base=frozenset({'peppers', 'avocado', 'sardines', 'nan'}), items_add=frozenset({'apples'}), confidence=0.9574468085106382, lift=3.0589354904493233)])
**********


RelationRecord(items=frozenset({'nan', 'peppers', 'apples', 'baguette', 'sardines'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baguette', 'peppers', 'sardines'}), items_add=frozenset({'apples', 'nan'}), confidence=0.9677419354838709, lift=3.0918272699165206), OrderedStatistic(items_base=frozenset({'baguette', 'nan', 'peppers', 'sardines'}), items_add=frozenset({'apples'}), confidence=0.9677419354838709, lift=3.0918272699165206)])
**********


RelationRecord(items=frozenset({'peppers', 'bourbon', 'apples', 'chicken', 'corned_b'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'chicken', 'bourbon', 'corned_b'}), items_add=frozenset({'peppers'}), confidence=0.9523809523809523, lift=3.2175032175032174)])
**********


RelationRecord(items=frozenset({'cracker', 'peppers', 'apples', 'chicken', 'corned_b'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'chicken', 'corned_b', 'cracker'}), items_add=frozenset({'peppers'}), confidence=0.9523809523809523, lift=3.2175032175032174)])
**********


RelationRecord(items=frozenset({'apples', 'corned_b', 'olives', 'ham', 'hering'}), support=0.031, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'ham', 'corned_b'}), items_add=frozenset({'olives', 'hering'}), confidence=1.0, lift=3.9215686274509802), OrderedStatistic(items_base=frozenset({'apples', 'ham', 'olives'}), items_add=frozenset({'corned_b', 'hering'}), confidence=0.96875, lift=3.9702868852459017)])
**********


RelationRecord(items=frozenset({'steak', 'apples', 'corned_b', 'olives', 'hering'}), support=0.096, ordered_statistics=[OrderedStatistic(items_base=frozenset({'apples', 'steak', 'corned_b'}), items_add=frozenset({'olives', 'hering'}), confidence=0.9504950495049505, lift=3.72743156668608), OrderedStatistic(items_base=frozenset({'apples', 'hering', 'steak'}), items_add=frozenset({'corned_b', 'olives'}), confidence=0.9795918367346939, lift=4.15081286751989), OrderedStatistic(items_base=frozenset({'apples', 'steak', 'olives'}), items_add=frozenset({'corned_b', 'hering'}), confidence=0.9795918367346939, lift=4.014720642355303)])
**********


RelationRecord(items=frozenset({'avocado', 'heineken', 'corned_b', 'ham', 'artichok'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corned_b', 'avocado', 'ham', 'heineken'}), items_add=frozenset({'artichok'}), confidence=0.9523809523809523, lift=3.12256049960968)])
**********


RelationRecord(items=frozenset({'cracker', 'avocado', 'heineken', 'ham', 'artichok'}), support=0.099, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cracker', 'ham', 'artichok'}), items_add=frozenset({'avocado', 'heineken'}), confidence=0.9801980198019802, lift=3.9365382321364666), OrderedStatistic(items_base=frozenset({'cracker', 'avocado', 'ham', 'heineken'}), items_add=frozenset({'artichok'}), confidence=0.9801980198019802, lift=3.2137639993507547)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'heineken', 'chicken', 'ice_crea'}), support=0.022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'coke', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9565217391304347, lift=3.055979997221836), OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'ice_crea', 'heineken'}), items_add=frozenset({'coke'}), confidence=0.9565217391304347, lift=3.2314923619271445)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'heineken', 'chicken', 'sardines'}), support=0.022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'coke', 'heineken'}), items_add=frozenset({'sardines'}), confidence=0.9565217391304347, lift=3.2314923619271445)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'chicken', 'sardines', 'ice_crea'}), support=0.022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'sardines', 'coke'}), items_add=frozenset({'ice_crea'}), confidence=1.0, lift=3.194888178913738), OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'sardines', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=1.0, lift=3.3783783783783785)])
**********


RelationRecord(items=frozenset({'cracker', 'peppers', 'bourbon', 'corned_b', 'chicken'}), support=0.092, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corned_b', 'chicken', 'peppers'}), items_add=frozenset({'cracker', 'bourbon'}), confidence=0.9583333333333333, lift=3.9930555555555554), OrderedStatistic(items_base=frozenset({'corned_b', 'chicken', 'bourbon', 'cracker'}), items_add=frozenset({'peppers'}), confidence=0.989247311827957, lift=3.3420517291485035), OrderedStatistic(items_base=frozenset({'corned_b', 'cracker', 'bourbon', 'peppers'}), items_add=frozenset({'chicken'}), confidence=0.989247311827957, lift=3.1404676565966887)])
**********


RelationRecord(items=frozenset({'heineken', 'bourbon', 'chicken', 'sardines', 'ice_crea'}), support=0.022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'bourbon', 'ice_crea', 'heineken'}), items_add=frozenset({'sardines'}), confidence=0.9565217391304347, lift=3.2314923619271445)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'heineken', 'sardines', 'ice_crea'}), support=0.023, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'bourbon', 'sardines', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9583333333333333, lift=3.0617678381256654), OrderedStatistic(items_base=frozenset({'heineken', 'bourbon', 'sardines', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=0.9583333333333333, lift=3.2376126126126126)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'nan', 'turkey', 'ice_crea'}), support=0.096, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'bourbon', 'turkey'}), items_add=frozenset({'nan', 'ice_crea'}), confidence=0.9795918367346939, lift=3.12968637934407), OrderedStatistic(items_base=frozenset({'ice_crea', 'bourbon', 'turkey'}), items_add=frozenset({'coke', 'nan'}), confidence=0.9696969696969697, lift=3.2760032760032765), OrderedStatistic(items_base=frozenset({'coke', 'bourbon', 'turkey', 'nan'}), items_add=frozenset({'ice_crea'}), confidence=0.9795918367346939, lift=3.12968637934407), OrderedStatistic(items_base=frozenset({'ice_crea', 'bourbon', 'turkey', 'nan'}), items_add=frozenset({'coke'}), confidence=0.9696969696969697, lift=3.2760032760032765)])
**********


RelationRecord(items=frozenset({'coke', 'bourbon', 'turkey', 'olives', 'ice_crea'}), support=0.094, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke', 'bourbon', 'turkey'}), items_add=frozenset({'olives', 'ice_crea'}), confidence=0.9591836734693877, lift=6.1882817643186305), OrderedStatistic(items_base=frozenset({'olives', 'coke', 'bourbon', 'ice_crea'}), items_add=frozenset({'turkey'}), confidence=0.9690721649484536, lift=3.4242832683690945), OrderedStatistic(items_base=frozenset({'olives', 'coke', 'bourbon', 'turkey'}), items_add=frozenset({'ice_crea'}), confidence=0.9894736842105263, lift=3.1612577770304355), OrderedStatistic(items_base=frozenset({'olives', 'ice_crea', 'bourbon', 'turkey'}), items_add=frozenset({'coke'}), confidence=0.9791666666666666, lift=3.3079954954954953)])
**********


RelationRecord(items=frozenset({'bourbon', 'turkey', 'corned_b', 'ham', 'hering'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corned_b', 'ham', 'bourbon', 'hering'}), items_add=frozenset({'turkey'}), confidence=0.9523809523809523, lift=3.365303718660609), OrderedStatistic(items_base=frozenset({'corned_b', 'hering', 'bourbon', 'turkey'}), items_add=frozenset({'ham'}), confidence=1.0, lift=3.278688524590164)])
**********


RelationRecord(items=frozenset({'cracker', 'heineken', 'bourbon', 'soda', 'hering'}), support=0.036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cracker', 'heineken', 'bourbon', 'hering'}), items_add=frozenset({'soda'}), confidence=0.9729729729729729, lift=3.0596634370219276)])
**********


RelationRecord(items=frozenset({'cracker', 'heineken', 'bourbon', 'soda', 'olives'}), support=0.106, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cracker', 'heineken', 'bourbon', 'olives'}), items_add=frozenset({'soda'}), confidence=0.9724770642201834, lift=3.0581039755351678)])
**********


RelationRecord(items=frozenset({'bourbon', 'turkey', 'olives', 'ham', 'hering'}), support=0.021, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olives', 'ham', 'bourbon', 'hering'}), items_add=frozenset({'turkey'}), confidence=0.9545454545454547, lift=3.3729521362030206)])
**********


RelationRecord(items=frozenset({'coke', 'heineken', 'chicken', 'ham', 'ice_crea'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ham', 'ice_crea'}), items_add=frozenset({'coke', 'heineken'}), confidence=0.9523809523809523, lift=5.473453749315818), OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'ham', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=1.0, lift=3.194888178913738), OrderedStatistic(items_base=frozenset({'ice_crea', 'chicken', 'ham', 'heineken'}), items_add=frozenset({'coke'}), confidence=1.0, lift=3.3783783783783785)])
**********


RelationRecord(items=frozenset({'coke', 'heineken', 'chicken', 'sardines', 'ham'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'ham', 'heineken'}), items_add=frozenset({'sardines'}), confidence=1.0, lift=3.3783783783783785), OrderedStatistic(items_base=frozenset({'chicken', 'sardines', 'ham', 'heineken'}), items_add=frozenset({'coke'}), confidence=1.0, lift=3.3783783783783785), OrderedStatistic(items_base=frozenset({'coke', 'sardines', 'ham', 'heineken'}), items_add=frozenset({'chicken'}), confidence=0.9523809523809523, lift=3.023431594860166)])
**********


RelationRecord(items=frozenset({'coke', 'nan', 'chicken', 'ham', 'ice_crea'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ham', 'ice_crea'}), items_add=frozenset({'coke', 'nan'}), confidence=0.9523809523809523, lift=3.2175032175032174), OrderedStatistic(items_base=frozenset({'chicken', 'nan', 'ham', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=0.9523809523809523, lift=3.2175032175032174)])
**********


RelationRecord(items=frozenset({'coke', 'chicken', 'sardines', 'ham', 'ice_crea'}), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'ham', 'ice_crea'}), items_add=frozenset({'coke', 'sardines'}), confidence=0.9523809523809523, lift=6.4787819889860705), OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'ham', 'ice_crea'}), items_add=frozenset({'sardines'}), confidence=1.0, lift=3.3783783783783785), OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'sardines', 'ham'}), items_add=frozenset({'ice_crea'}), confidence=1.0, lift=3.194888178913738), OrderedStatistic(items_base=frozenset({'chicken', 'sardines', 'ham', 'ice_crea'}), items_add=frozenset({'coke'}), confidence=1.0, lift=3.3783783783783785), OrderedStatistic(items_base=frozenset({'coke', 'sardines', 'ham', 'ice_crea'}), items_add=frozenset({'chicken'}), confidence=0.9523809523809523, lift=3.023431594860166)])
**********


RelationRecord(items=frozenset({'coke', 'nan', 'heineken', 'chicken', 'ice_crea'}), support=0.116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'heineken'}), items_add=frozenset({'nan', 'ice_crea'}), confidence=0.9830508474576273, lift=3.140737531813506), OrderedStatistic(items_base=frozenset({'chicken', 'ice_crea', 'heineken'}), items_add=frozenset({'coke', 'nan'}), confidence=0.9747899159663866, lift=3.2932091755621173), OrderedStatistic(items_base=frozenset({'chicken', 'coke', 'nan', 'heineken'}), items_add=frozenset({'ice_crea'}), confidence=0.9830508474576273, lift=3.140737531813506), OrderedStatistic(items_base=frozenset({'chicken', 'nan', 'ice_crea', 'heineken'}), items_add=frozenset({'coke'}), confidence=0.9747899159663866, lift=3.2932091755621173)])
**********




# market pasket analysis using ECLAT algorithm

In [1]:
from pyECLAT import Example1, Example2
ex1 = Example1().get()
ex2 = Example2().get()
ex1
ex2
from pyECLAT import ECLAT
eclat_instance = ECLAT(data=ex1, verbose=True) #verbose=True to see the loading bar

100%|██████████| 7/7 [00:00<00:00, 75.91it/s]
100%|██████████| 7/7 [00:00<?, ?it/s]
100%|██████████| 7/7 [00:00<00:00, 874.59it/s]

In [2]:
import pandas as pd

In [3]:
ex1
from pyECLAT import ECLAT
eclat_instance = ECLAT(data=ex2, verbose=True) #verbose=True to see the loading bar

100%|██████████| 119/119 [00:00<00:00, 120.71it/s]
100%|██████████| 119/119 [00:00<00:00, 2974.86it/s]
100%|██████████| 119/119 [00:00<00:00, 1083.02it/s]

In [4]:
ex2

,0,1,2,3,4,5,6
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN
...,...,...,...,...,...,...,...
2996,green tea,NaN,NaN,NaN,NaN,NaN,NaN
2997,shrimp,cake,NaN,NaN,NaN,NaN,NaN
2998,ham,ground beef,mineral water,NaN,NaN,NaN,NaN
2999,burgers,frozen vegetables,whole wheat pasta,mineral water,chocolate,eggs,blueberries
3000,whole wheat pasta,eggs,cake,french fries,green tea,NaN,NaN

In [5]:
ex1

        0      1       2       3
0    milk   beer   bread  butter
1   coffe  bread  butter     NaN
2   coffe  bread  butter     NaN
3    milk  coffe   bread  butter
4    beer    NaN     NaN     NaN
5  butter    NaN     NaN     NaN
6   bread    NaN     NaN     NaN
7    bean    NaN     NaN     NaN
8    rice   bean     NaN     NaN
9    rice    NaN     NaN     NaN

In [6]:
# Data Preprocessing
dataset_eclat=pd.read_csv('E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/work1.csv')
dataset_eclat

,nan,nan.1,nan.2,nan.3,nan.4,bourbon,nan.5,nan.6,corned_b,nan.7,ham,nan.8,hering,ice_crea,olives,nan.9,nan.10,nan.11,nan.12,turkey
0,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,cracker,NaN,heineken,hering,NaN,olives,NaN,NaN,soda,NaN,NaN
1,NaN,artichok,avocado,NaN,NaN,NaN,NaN,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,sardines,NaN,NaN,turkey
2,NaN,NaN,NaN,NaN,NaN,bourbon,NaN,coke,NaN,NaN,ham,NaN,NaN,ice_crea,olives,peppers,NaN,NaN,NaN,turkey
3,apples,NaN,avocado,NaN,NaN,NaN,NaN,NaN,corned_b,NaN,NaN,NaN,hering,NaN,olives,NaN,NaN,NaN,steak,turkey
4,NaN,NaN,NaN,NaN,NaN,NaN,chicken,coke,NaN,NaN,ham,heineken,NaN,ice_crea,NaN,peppers,sardines,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,artichok,avocado,NaN,NaN,bourbon,chicken,NaN,NaN,cracker,ham,heineken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,apples,NaN,NaN,baguette,NaN,NaN,NaN,NaN,corned_b,NaN,ham,NaN,hering,NaN,olives,NaN,NaN,NaN,NaN,turkey
997,NaN,NaN,NaN,baguette,NaN,NaN,NaN,NaN,NaN,cracker,NaN,heineken,hering,NaN,NaN,NaN,sardines,soda,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,chicken,coke,corned_b,NaN,NaN,heineken,NaN,ice_crea,NaN,peppers,sardines,NaN,NaN,NaN
999,apples,NaN,NaN,NaN,NaN,bourbon,NaN,NaN,corned_b,NaN,NaN,heineken,hering,NaN,olives,NaN,NaN,NaN,steak,NaN

In [7]:
from pyECLAT import ECLAT
eclat_instance = ECLAT(data=dataset_eclat, verbose=True) #verbose=True to see the loading bar

  0%|          | 0/20 [00:00<?, ?it/s]

KeyError: 0

# market basket analysis using eclat algorith

In [1]:
import pandas as pd
dataframe = pd.read_excel('E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/na_dataset.xlsx', header = None)
dataframe

                  0           1     2      3     4     5     6
0     transaction #  vegetables  baby  fruit  milk  dvds  meat
1                 1        vege   NaN    NaN  milk   NaN  meat
2                 2        vege  baby  fruit  milk   NaN   NaN
3                 3        vege   NaN    NaN   NaN   NaN   NaN
4                 4        vege   NaN  fruit   NaN   NaN   NaN
...             ...         ...   ...    ...   ...   ...   ...
2924           2924        vege   NaN  fruit   NaN   NaN   NaN
2925           2925        vege   NaN  fruit   NaN   NaN   NaN
2926           2926        vege   NaN  fruit   NaN   NaN   NaN
2927           2927        vege   NaN    NaN  milk   NaN   NaN
2928           2928        vege   NaN    NaN  milk   NaN   NaN

[2929 rows x 7 columns]

In [5]:
dataframe.describe().transpose()

  count unique            top  freq
0  2929   2929  transaction #     1
1  1777      2           vege  1776
2   795      1           baby   795
3   870      1          fruit   870
4   890      1           milk   890
5   619      1           dvds   619
6   731      1           meat   731

In [2]:
from pyECLAT import ECLAT
eclat_instance = ECLAT(data=dataframe, verbose=True) #verbose=True to see the loading bar

100%|██████████| 2936/2936 [00:23<00:00, 124.98it/s]
100%|██████████| 2936/2936 [00:00<00:00, 4138.33it/s]
100%|██████████| 2936/2936 [00:02<00:00, 1386.51it/s]

In [3]:
eclat_instance.df_bin   #generate a binary dataframe, that can be used for other analyzes.
eclat_instance.uniq_    #a list with all the names of the different items

[nan,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [4]:
get_ECLAT_indexes, get_ECLAT_supports = eclat_instance.fit(min_support=0.02,
                                                           min_combination=1,
                                                           max_combination=6,
                                                           separator=' & ',
                                                           verbose=True)

0it [00:00, ?it/s]

Combination 1 by 1

6it [00:00,  7.98it/s]
2it [00:00, 14.17it/s]

Combination 2 by 2

15it [00:00, 16.18it/s]
3it [00:00, 26.85it/s]

Combination 3 by 3

20it [00:00, 28.11it/s]
5it [00:00, 49.96it/s]

Combination 4 by 4

15it [00:00, 56.78it/s]
6it [00:00, 66.62it/s]
1it [00:00, 49.97it/s]

Combination 5 by 5
Combination 6 by 6

In [29]:
help(eclat_instance.fit)
help(eclat_instance.fit_all)
help(eclat_instance.support)

Help on method fit in module pyECLAT.pyECLAT:

fit(min_support=0.08, min_combination=1, max_combination=3, separator=' & ', verbose=True) method of pyECLAT.pyECLAT.ECLAT instance
    Return a dictionary. The key is the feature and value is support. A high number of
    combinations (greater than three) can take a long time to finish.


    Arguments
    ---------------------
    min_support
        Must be 'None' to return all features and supports or 'Float' to filter features by support
    min_combination
        Minimal combination of attributes
    max_combination
        Maximum combination of attributes
    separator
        Separator for the output dictionary key. Just to organize. default = ' & '
    verbose
        `True` to enable the loading bar.

Help on method fit_all in module pyECLAT.pyECLAT:

fit_all(min_support=0.08, separator=' & ', verbose=False, min_combination=1) method of pyECLAT.pyECLAT.ECLAT instance
    Return a dictionary. The key is the feature and value is support.
    This algorithm works with all possible permutations (without repetitions)
    until the all supports = 0.

    Arguments
    ---------------------
    min_support
        Must be 'None' to return all features and supports or 'Float' to filter features by support
    separator
        Separator for the output dictionary key. Just to organize. default = ' & '
    verbose
        `True` to enables the loading bar.

Help on method support in module pyECLAT.pyECLAT:

support(min_support=None) method of pyECLAT.pyECLAT.ECLAT instance
    Return a dictionary. The key is the feature and value is support

    Arguments
    ---------------------
    min_support
        Must be 'None' to return all features and supports or 'Float' to filter features by support

# end of eclat

In [12]:
import pandas as pd
dataframe12 = pd.read_excel('E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/na_datasets.xlsx', header = None)
dataframe12

                  0           1     2      3     4     5     6
0     transaction #  vegetables  baby  fruit  milk  dvds  meat
1                 1        vege     0      0  milk     0  meat
2                 2        vege  baby  fruit  milk     0     0
3                 3        vege     0      0     0     0     0
4                 4        vege     0  fruit     0     0     0
...             ...         ...   ...    ...   ...   ...   ...
2924           2924        vege     0  fruit     0     0     0
2925           2925        vege     0  fruit     0     0     0
2926           2926        vege     0  fruit     0     0     0
2927           2927        vege     0      0  milk     0     0
2928           2928        vege     0      0  milk     0     0

[2929 rows x 7 columns]

In [13]:
transactions=[]
for i in range(0,2929):
    transactions.append([str(dataframe12.values[i,j]) for j in range(0,6)])

In [14]:
rule_list12 = apriori(transactions, min_support = 0.02, min_confidence = 0.95, min_lift = 0, min_length = 2)

In [15]:
# Visualizing the list of rules
results = list(rule_list12)
for i in results:
    print('\n')
    print(i)
    print('**********')

RelationRecord(items=frozenset({'0'}), support=0.99522021167634, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'0'}), confidence=0.99522021167634, lift=1.0)])
**********


RelationRecord(items=frozenset({'0', 'baby'}), support=0.26664390576988733, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baby'}), items_add=frozenset({'0'}), confidence=0.9823899371069182, lift=0.9871081049009138)])
**********


RelationRecord(items=frozenset({'0', 'dvds'}), support=0.20655513827244792, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dvds'}), items_add=frozenset({'0'}), confidence=0.9773828756058157, lift=0.9820769957630993)])
**********


RelationRecord(items=frozenset({'0', 'fruit'}), support=0.2922499146466371, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fruit'}), items_add=frozenset({'0'}), confidence=0.9839080459770115, lift=0.9886335048599201)])
**********


RelationRecord(items=frozenset({'milk', '0'}), support=0.299078183680437, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'0'}), confidence=0.9842696629213482, lift=0.9889968585580202)])
**********


RelationRecord(items=frozenset({'0', 'vege'}), support=0.601911915329464, ordered_statistics=[OrderedStatistic(items_base=frozenset({'vege'}), items_add=frozenset({'0'}), confidence=0.9926801801801801, lift=0.9974477693817316)])
**********


RelationRecord(items=frozenset({'vege', '0', 'baby'}), support=0.15397746671218845, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baby', 'vege'}), items_add=frozenset({'0'}), confidence=0.9719827586206896, lift=0.9766509433962264)])
**********


RelationRecord(items=frozenset({'0', 'dvds', 'vege'}), support=0.11847046773642882, ordered_statistics=[OrderedStatistic(items_base=frozenset({'vege', 'dvds'}), items_add=frozenset({'0'}), confidence=0.9638888888888889, lift=0.9685182008766915)])
**********


RelationRecord(items=frozenset({'0', 'fruit', 'vege'}), support=0.17309662000682827, ordered_statistics=[OrderedStatistic(items_base=frozenset({'vege', 'fruit'}), items_add=frozenset({'0'}), confidence=0.975, lift=0.9796826758147513)])
**********


RelationRecord(items=frozenset({'milk', '0', 'vege'}), support=0.1795834755889382, ordered_statistics=[OrderedStatistic(items_base=frozenset({'milk', 'vege'}), items_add=frozenset({'0'}), confidence=0.9758812615955472, lift=0.9805681698845139)])
**********

In [17]:
data1=pd.read_excel("E:/4th sem/4. ma-II/3rd unit/MA-Winston Wayne-Chapter 29 Excel files/marketbasketdata.xls")
data1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,apples,artichok,avocado,baguette,bordeaux,bourbon,chicken,coke,corned_b,...,ham,heineken,hering,ice_crea,olives,peppers,sardines,soda,steak,turkey
4,NaN,0,0,0,0,0,1,0,0,1,...,1,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,NaN,0,1,1,0,0,1,1,0,0,...,1,1,0,0,0,0,0,0,0,0
1001,NaN,1,0,0,1,0,0,0,0,1,...,1,0,1,0,1,0,0,0,0,1
1002,NaN,0,0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,1,1,0,0
1003,NaN,0,0,0,0,0,0,1,1,1,...,0,1,0,1,0,1,1,0,0,0
1004,NaN,1,0,0,0,0,1,0,0,1,...,0,1,1,0,1,0,0,0,1,0

In [19]:
from pyECLAT import ECLAT
eclat_instance = ECLAT(data=data1, verbose=True) #verbose=True to see the loading bar

  0%|          | 0/23 [00:00<?, ?it/s]

KeyError: 0